/** Auto-generated by scripts/generate-all-images.ts — do not edit by hand */
export type GeneratedMap = Record<string, string>;

const generatedMap: GeneratedMap = {};

export default generatedMap;

export function resolveImageSrc(slotId: string, fallbackSrc: string): string {
  return generatedMap[slotId] || fallbackSrc;
}
